import './globals.css'

export const metadata = {
  title: 'Digital Tools',
  description: 'Generated by hard work',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
